srun: error: hhnode-ib-104: task 1: Killed
srun: error: hhnode-ib-104: task 5: Killed
srun: error: hhnode-ib-104: task 0: Killed
srun: error: hhnode-ib-104: task 2: Killed
srun: error: hhnode-ib-104: task 4: Killed
srun: error: hhnode-ib-104: task 8: Killed
srun: error: hhnode-ib-104: task 6: Killed
Initialising
finished generation
cuda {'excel_path': 'patient-clinical-data.xlsx', 'patches_path': 'patches', 'classification_label': 'ER', 'positive_label': 'Positive', 'bag_size': 30, 'train_ratio': 0.8, 'optimizer': 'Adam', 'epoch': 3}
Initialising
finished generation
cuda {'excel_path': 'patient-clinical-data.xlsx', 'patches_path': 'patches', 'classification_label': 'ER', 'positive_label': 'Positive', 'bag_size': 30, 'train_ratio': 0.8, 'optimizer': 'Adam', 'epoch': 3}
Initialising
finished generation
cuda {'excel_path': 'patient-clinical-data.xlsx', 'patches_path': 'patches', 'classification_label': 'ER', 'positive_label': 'Positive', 'bag_size': 30, 'train_ratio': 0.8, 'optimizer': 'Adam', 'epoch': 3}
Traceback (most recent call last):
  File "train.py", line 100, in <module>
    bag_class = model(device_patch)
  File "/home/kcyipae/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kcyipae/code/BCNB Dataset/models.py", line 68, in forward
    feat = self.cnn(bag) # N * 3 * 256 * 256 -> N * 512 * 7 * 7
  File "/home/kcyipae/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kcyipae/code/BCNB Dataset/models.py", line 13, in forward
    feat = self.extractor(x)
  File "/home/kcyipae/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kcyipae/.local/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/kcyipae/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kcyipae/.local/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/kcyipae/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kcyipae/.local/lib/python3.8/site-packages/torch/nn/modules/batchnorm.py", line 168, in forward
    return F.batch_norm(
  File "/home/kcyipae/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 2438, in batch_norm
    return torch.batch_norm(
RuntimeError: CUDA out of memory. Tried to allocate 104.00 MiB (GPU 0; 10.76 GiB total capacity; 3.10 GiB already allocated; 26.56 MiB free; 3.19 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "train.py", line 100, in <module>
    bag_class = model(device_patch)
  File "/home/kcyipae/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kcyipae/code/BCNB Dataset/models.py", line 68, in forward
    feat = self.cnn(bag) # N * 3 * 256 * 256 -> N * 512 * 7 * 7
  File "/home/kcyipae/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kcyipae/code/BCNB Dataset/models.py", line 13, in forward
    feat = self.extractor(x)
  File "/home/kcyipae/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kcyipae/.local/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/kcyipae/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kcyipae/.local/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/kcyipae/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kcyipae/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/kcyipae/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 240.00 MiB (GPU 0; 10.76 GiB total capacity; 2.33 GiB already allocated; 130.56 MiB free; 2.34 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "train.py", line 100, in <module>
    bag_class = model(device_patch)
  File "/home/kcyipae/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kcyipae/code/BCNB Dataset/models.py", line 68, in forward
    feat = self.cnn(bag) # N * 3 * 256 * 256 -> N * 512 * 7 * 7
  File "/home/kcyipae/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kcyipae/code/BCNB Dataset/models.py", line 13, in forward
    feat = self.extractor(x)
  File "/home/kcyipae/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kcyipae/.local/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/kcyipae/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kcyipae/.local/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/kcyipae/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kcyipae/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/kcyipae/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 240.00 MiB (GPU 0; 10.76 GiB total capacity; 2.33 GiB already allocated; 130.56 MiB free; 2.34 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
srun: error: hhnode-ib-104: task 3: Exited with exit code 1
srun: error: hhnode-ib-104: task 7: Exited with exit code 1
srun: error: hhnode-ib-104: task 9: Exited with exit code 1
srun: Force Terminated job step 738457.0
